Fix/adding https enable flag
snyk/snyk-broker-helm pull request #110
Opened 2024-03-15 15:09 UTC by saumilmac

What:
- Adding a flag to enable HTTPS

2024-03-20 15:49 UTC, soniqua requested changes

2024-03-20 15:49 UTC, soniqua commented on charts/snyk-broker/values.yaml
> +enableBrokerServerOverHttps: false
```suggestion
forceHttps: false
```

2024-03-20 15:49 UTC, soniqua commented on charts/snyk-broker/templates/broker_deployment.yaml
> +              {{- if .Values.enableBrokerServerOverHttps }}
This changes existing behaviour - we should maintain backwards compatibility:

```suggestion
              {{- if or ( and (.Values.httpsCert) (.Values.httpsKey) ) ( .Values.enableBrokerServerOverHttps ) ) }}
```

2024-03-20 15:50 UTC, soniqua commented on charts/snyk-broker/values.yaml
> +enableBrokerServerOverHttps: false
We should consider adding a snapshot for this too.

2024-03-20 16:52 UTC, saumilmac commented on charts/snyk-broker/values.yaml
> +enableBrokerServerOverHttps: false
I can add a snapshot for this. @aarlaud any thoughts on the name here ?

2024-03-20 16:53 UTC, aarlaud commented on charts/snyk-broker/values.yaml
> +enableBrokerServerOverHttps: false
It was meant to be BrokerServe not BrokerServer. It's for the local broker server running in the client. Referencing broker server is confusing here, but broker client, which most people refer to broker, then does server over https.
Ideally it should be enableBrokerLocalWebserverOverHttps. Maybe we just use that long name so it's clearer?

2024-03-20 16:55 UTC, saumilmac commented on charts/snyk-broker/templates/broker_deployment.yaml
> +              {{- if .Values.enableBrokerServerOverHttps }}
@soniqua I see your point but my thought process here was keep a single flag to choose between https vs http. If httpsEnabled flag is set httpsCert and httpsKey are mandatory.

2024-03-20 16:55 UTC, soniqua commented on charts/snyk-broker/values.yaml
> +enableBrokerServerOverHttps: false
A longer name is not an issue. The main problem was `server` as opposed to `serve`.

2024-03-20 17:06 UTC, saumilmac commented on charts/snyk-broker/templates/broker_deployment.yaml
> +              {{- if .Values.enableBrokerServerOverHttps }}
ahh from that lens, yes extra value will be required. I see your point now, I ll add the double conditional. But for the new hybrid platform chart we should keep a single flag to enable/disable something.

2024-03-20 19:13 UTC, saumilmac commented on charts/snyk-broker/values.yaml
> +enableBrokerServerOverHttps: false
fixed

2024-03-20 20:35 UTC, aarlaud approved these changes

2024-03-21 09:35 UTC, soniqua approved these changes

2024-03-21 13:35 UTC, merged