fix: adds labels to broker deployment
snyk/snyk-broker-helm pull request #120
Opened 2024-06-19 18:12 UTC by saumilmac

What:
- Adds additional labels to snyk-broker-deployment

2024-06-20 12:39 UTC, soniqua requested changes
Please add tests to validate this new functionality

2024-06-21 10:42 UTC, soniqua requested changes

2024-06-21 10:42 UTC, soniqua commented on charts/snyk-broker/templates/_helpers.tpl
> +{{  toYaml . }}
q: How does this handle duplicate labels? May need to use a `merge` with override/discard any common labels that are already set.

2024-06-24 16:38 UTC, saumilmac commented on charts/snyk-broker/templates/_helpers.tpl
> +{{  toYaml . }}
fixed

2024-06-24 16:58 UTC, aarlaud submitted a review, later dismissed

2024-06-25 09:04 UTC, soniqua commented on charts/snyk-broker/templates/_helpers.tpl
> +{{- $commonLabels = merge $commonLabels . }}
q: confirming this behaviour is as expected:

- Any labels provided in `.Values.labels` are overridden if they already exist in our standard definition
- Any new labels in `.Values.labels` are added

2024-06-25 11:42 UTC, saumilmac commented on charts/snyk-broker/templates/_helpers.tpl
> +{{- $commonLabels = merge $commonLabels . }}
Correct, I merged the tests to add new labels and test if any labels provided in .Values.labels are overridden if they already exist. Snapshots showing that results.

2024-06-25 12:45 UTC, soniqua commented on charts/snyk-broker/values.yaml
> +# Adds additional labels to broker deployment
q: Does this impact the CRA deployment too?

2024-06-25 12:45 UTC, soniqua commented on charts/snyk-broker/tests/fixtures/default_values.yaml
> +brokerDispatcherUrl: "https://api.test.snyk.io"
nit: Ensure there's a newline here

2024-06-25 12:45 UTC, soniqua commented on charts/snyk-broker/tests/broker_deployment_test.yaml
> +      - matchSnapshot: {}
enh: asserting the label is present as opposed to an entire snapshot helps ensure this test is valid and not impacted by any future changes

2024-06-25 12:59 UTC, saumilmac commented on charts/snyk-broker/values.yaml
> +# Adds additional labels to broker deployment
This doesn't impact CRA deployment. For CRA labels are static and not driven through the helper function 
https://github.com/snyk/snyk-broker-helm/blob/main/charts/snyk-broker/templates/cra_deployment.yaml#L7-L9

2024-06-25 15:51 UTC, saumilmac commented on charts/snyk-broker/tests/fixtures/default_values.yaml
> +brokerDispatcherUrl: "https://api.test.snyk.io"
updated

2024-06-25 15:52 UTC, saumilmac commented on charts/snyk-broker/tests/broker_deployment_test.yaml
> +      - matchSnapshot: {}
I used `equals`, since labels are a map and `contains` require an array.

2024-06-27 08:42 UTC, soniqua approved these changes

2024-06-27 16:06 UTC, merged