fix: make broker servicename k8s api compliant[HYB-584]
snyk/snyk-broker-helm pull request #124
Opened 2024-07-25 15:49 UTC by saumilmac

Adds:
- Makes broker service name k8s compliant

2024-07-26 08:07 UTC, soniqua requested changes
Some changes needed here - appreciate this is draft so might still be in progress.

Please make sure we address the CRA service name (as I believe that's the longest service name we might create): `container-registry-agent-broker-service-snyk-broker-container-default`

2024-07-26 08:07 UTC, soniqua commented on charts/snyk-broker/templates/_helpers.tpl
>  {{- if not .Values.disableSuffixes -}}
req: `disableSuffixes` doesn't exist in either `values.yaml` or `values.schema.json` - we should add this and explain what it actually does

2024-07-26 08:07 UTC, soniqua commented on charts/snyk-broker/templates/_helpers.tpl
> +{{- $suffixLength := 16 -}}
req: This is misleading, `suffix` is `.Release.Name` - can this be renamed please? I believe after reading this helper the length of 16 refers to `-broker-service-`.

2024-07-26 08:07 UTC, soniqua commented on charts/snyk-broker/templates/_helpers.tpl
> +{{- .Values.scmType | trunc $truncatedLength }}-broker-service-{{ .Release.Name }}
req: Please add tests for this

2024-07-29 23:40 UTC, saumilmac commented on charts/snyk-broker/templates/_helpers.tpl
>  {{- if not .Values.disableSuffixes -}}
added. I wonder if we still need this variable. do we know if any of our customers uses v1.0.0 of broker ?

2024-07-29 23:41 UTC, saumilmac commented on charts/snyk-broker/templates/_helpers.tpl
> +{{- .Values.scmType | trunc $truncatedLength }}-broker-service-{{ .Release.Name }}
added

2024-07-29 23:41 UTC, saumilmac commented on charts/snyk-broker/templates/_helpers.tpl
> +{{- $suffixLength := 16 -}}
fixed

2024-08-20 12:38 UTC, soniqua approved these changes
LGTM - I'll follow this up with some suffix cleanup activities

2024-08-20 12:41 UTC, soniqua commented
Oh, don't forget to bump the chart version please.

2024-08-29 18:08 UTC, merged